import 'package:flutter/widgets.dart';

import 'design_spec.dart';

/// 시험 중인 디자인 안 목록. 디버그 빌드의 디자인 전환 UI가 이 목록을 그린다.
///
/// 새 안을 시험하려면 여기에 [DesignSpec]을 하나 더 만들어 넣기만 하면 된다.
/// 화면 코드는 건드리지 않는다.
const designCatalog = <DesignSpec>[
  whiteCatalogSpec,
  warmKitchenSpec,
  midnightPrepSpec,
  crispPaperSpec,
  roomyKitchenSpec,
];

/// 앱이 켜질 때와 테마 없이 위젯만 띄우는 테스트에서 쓰이는 기본 안.
const defaultDesignSpec = whiteCatalogSpec;

// ---------------------------------------------------------------------------
// 0. 화이트 카탈로그 — 넷플릭스식 카드 홈(메인 저장소 PR #63)과 같은 팔레트
// ---------------------------------------------------------------------------

/// 흰 바탕 + 버밀리언 주황 포인트. 사진을 카드로 늘어놓는 화면에서는 바탕에
/// 색이 섞여 있으면 음식 사진과 싸운다 — 흰 바탕이 사진을 앞으로 낸다.
/// 중성색은 아주 살짝 차갑게 잡는다. 크림 계열을 남기면 흰 바탕이 탁해 보인다.
const whiteCatalogSpec = DesignSpec(
  id: 'white-catalog',
  label: '화이트 카탈로그',
  palette: DesignPalette(
    brightness: Brightness.light,
    ink: Color(0xFF17130F),
    slate: Color(0xFF55504B),
    muted: Color(0xFF8D867F),
    surface: Color(0xFFFFFFFF),
    card: Color(0xFFFFFFFF),
    line: Color(0xFFE4E2E4),
    accent: Color(0xFFF04E23),
    accentSoft: Color(0xFFFDEDE8),
    onAccent: Color(0xFFFFFFFF),
    wash: Color(0xFFF4F4F6),
    success: Color(0xFF5C8A4E),
    shadow: Color(0x1A17130F),
    inverseSurface: Color(0xFF17130F),
    onInverse: Color(0xFFFFFFFF),
    onInverseMuted: Color(0xB3FFFFFF),
    inverseLine: Color(0x33FFFFFF),
    scrimStrong: Color(0xCC17130F),
    scrimSoft: Color(0x6617130F),
    overlaySurface: Color(0xD9FFFFFF),
    // 사진 플레이스홀더만 웜 톤을 남긴다 — 음식 자리라는 힌트다.
    placeholderFrom: Color(0xFFFBEBD9),
    placeholderTo: Color(0xFFF3D8BC),
    placeholderIcon: Color(0xFFC08A5A),
  ),
  type: DesignTypography(
    fontFamily: 'Pretendard',
    tightTracking: -0.6,
    bodyHeight: 1.5,
    displayHeight: 1.15,
    regular: FontWeight.w400,
    medium: FontWeight.w500,
    semiBold: FontWeight.w600,
    bold: FontWeight.w700,
    extraBold: FontWeight.w800,
    black: FontWeight.w900,
    microSize: 9,
    tinySize: 11,
    smallSize: 12,
    captionSize: 13,
    bodySize: 14,
    labelSize: 15,
    bodyLargeSize: 16,
    leadSize: 18,
    titleSize: 20,
    titleLargeSize: 23,
    heroTitleSize: 26,
    headlineSize: 28,
    headlineLargeSize: 32,
    numericSize: 44,
  ),
  density: DesignDensity(
    hairGap: 3,
    tightGap: 6,
    snugGap: 8,
    itemGap: 10,
    blockGap: 12,
    sectionGap: 18,
    majorGap: 24,
    sectionBreak: 48,
    screenPaddingX: 20,
    screenPaddingTop: 16,
    screenPaddingBottom: 24,
    cardPadding: 16,
    chipPaddingX: 8,
    chipPaddingY: 4,
    radiusSm: 8,
    radiusMd: 12,
    radiusLg: 14,
    radiusXl: 20,
    radiusPill: 999,
    controlHeight: 56,
    compactControlHeight: 48,
    tapTarget: 48,
    contentMaxWidth: 480,
    iconSm: 16,
    iconMd: 18,
    iconLg: 22,
    iconXl: 32,
    iconHero: 40,
    thumbSize: 76,
    brandMarkSize: 64,
    avatarSize: 44,
    avatarLargeSize: 54,
    shadowBlur: 22,
    shadowLift: 8,
    softShadowBlur: 14,
    softShadowLift: 4,
    overlayButtonSize: 38,
    cookControlSize: 96,
    heroImageHeight: 300,
    stepImageHeight: 210,
    photoTileSize: 88,
  ),
);

// ---------------------------------------------------------------------------
// 1. 따뜻한 키친 — 지금까지 써 온 디자인
// ---------------------------------------------------------------------------

/// 순검정·순백·차가운 회색을 쓰지 않고, 크림 바탕 위에 에스프레소 브라운과
/// 파프리카 포인트 하나로 통일한다. 회색 계열은 전부 웜 톤으로 맞춘다.
const _warmPalette = DesignPalette(
  brightness: Brightness.light,
  ink: Color(0xFF33261A),
  slate: Color(0xFF7A6A58),
  muted: Color(0xFFA8988A),
  surface: Color(0xFFFAF5EE),
  card: Color(0xFFFFFFFF),
  line: Color(0xFFEFE5D8),
  accent: Color(0xFFD4572E),
  accentSoft: Color(0xFFF9E8DD),
  onAccent: Color(0xFFFFFFFF),
  wash: Color(0xFFF5EDE2),
  success: Color(0xFF5C8A4E),
  shadow: Color(0x1F8A6A45),
  inverseSurface: Color(0xFF33261A),
  onInverse: Color(0xFFFFFFFF),
  onInverseMuted: Color(0xB3FFFFFF),
  inverseLine: Color(0x33FFFFFF),
  scrimStrong: Color(0xCC1F1209),
  scrimSoft: Color(0x66201005),
  overlaySurface: Color(0xD9FFFFFF),
  placeholderFrom: Color(0xFFFBEBD9),
  placeholderTo: Color(0xFFF3D8BC),
  placeholderIcon: Color(0xFFC08A5A),
);

const warmKitchenSpec = DesignSpec(
  id: 'warm-kitchen',
  label: '따뜻한 키친',
  palette: _warmPalette,
  type: DesignTypography(
    fontFamily: 'Pretendard',
    tightTracking: -0.6,
    bodyHeight: 1.5,
    displayHeight: 1.15,
    regular: FontWeight.w400,
    medium: FontWeight.w500,
    semiBold: FontWeight.w600,
    bold: FontWeight.w700,
    extraBold: FontWeight.w800,
    black: FontWeight.w900,
    microSize: 9,
    tinySize: 11,
    smallSize: 12,
    captionSize: 13,
    bodySize: 14,
    labelSize: 15,
    bodyLargeSize: 16,
    leadSize: 18,
    titleSize: 20,
    titleLargeSize: 23,
    heroTitleSize: 26,
    headlineSize: 28,
    headlineLargeSize: 32,
    numericSize: 44,
  ),
  density: DesignDensity(
    hairGap: 3,
    tightGap: 6,
    snugGap: 8,
    itemGap: 10,
    blockGap: 12,
    sectionGap: 18,
    majorGap: 24,
    sectionBreak: 48,
    screenPaddingX: 20,
    screenPaddingTop: 16,
    screenPaddingBottom: 24,
    cardPadding: 16,
    chipPaddingX: 8,
    chipPaddingY: 4,
    radiusSm: 8,
    radiusMd: 12,
    radiusLg: 14,
    radiusXl: 20,
    radiusPill: 999,
    controlHeight: 56,
    compactControlHeight: 48,
    tapTarget: 48,
    contentMaxWidth: 480,
    iconSm: 16,
    iconMd: 18,
    iconLg: 22,
    iconXl: 32,
    iconHero: 40,
    thumbSize: 76,
    brandMarkSize: 64,
    avatarSize: 44,
    avatarLargeSize: 54,
    shadowBlur: 22,
    shadowLift: 8,
    softShadowBlur: 14,
    softShadowLift: 4,
    overlayButtonSize: 38,
    cookControlSize: 96,
    heroImageHeight: 300,
    stepImageHeight: 210,
    photoTileSize: 88,
  ),
);

// ---------------------------------------------------------------------------
// 2. 미드나잇 프렙 — 색 축 실험 (어두운 주방)
// ---------------------------------------------------------------------------

/// 밤에 불 끄고 요리할 때를 상정한 어두운 안. 형태와 밀도는 [warmKitchenSpec]과
/// 같게 두어, 색만 바꿨을 때 화면이 어떻게 읽히는지를 따로 볼 수 있게 했다.
const midnightPrepSpec = DesignSpec(
  id: 'midnight-prep',
  label: '미드나잇 프렙',
  palette: DesignPalette(
    brightness: Brightness.dark,
    ink: Color(0xFFF2EAE0),
    slate: Color(0xFFB0A294),
    muted: Color(0xFF7C7065),
    surface: Color(0xFF16110D),
    card: Color(0xFF211A15),
    line: Color(0xFF33291F),
    accent: Color(0xFFF0803C),
    accentSoft: Color(0xFF3A2418),
    onAccent: Color(0xFF1A0F07),
    wash: Color(0xFF1D1712),
    success: Color(0xFF7FB56A),
    shadow: Color(0x8A000000),
    // 어두운 바탕에서는 밝은 카드가 강조가 된다. 명암 역할이 뒤집힌다.
    inverseSurface: Color(0xFFF2EAE0),
    onInverse: Color(0xFF16110D),
    onInverseMuted: Color(0xB316110D),
    inverseLine: Color(0x3316110D),
    scrimStrong: Color(0xE6000000),
    scrimSoft: Color(0x80000000),
    overlaySurface: Color(0xD9211A15),
    placeholderFrom: Color(0xFF2A211A),
    placeholderTo: Color(0xFF3A2E24),
    placeholderIcon: Color(0xFF8A7259),
  ),
  type: DesignTypography(
    fontFamily: 'Pretendard',
    tightTracking: -0.6,
    bodyHeight: 1.5,
    displayHeight: 1.15,
    // 어두운 바탕에서는 같은 굵기가 더 두껍게 보여, 한 단계씩 낮춰 잡는다.
    regular: FontWeight.w400,
    medium: FontWeight.w400,
    semiBold: FontWeight.w500,
    bold: FontWeight.w600,
    extraBold: FontWeight.w700,
    black: FontWeight.w800,
    microSize: 9,
    tinySize: 11,
    smallSize: 12,
    captionSize: 13,
    bodySize: 14,
    labelSize: 15,
    bodyLargeSize: 16,
    leadSize: 18,
    titleSize: 20,
    titleLargeSize: 23,
    heroTitleSize: 26,
    headlineSize: 28,
    headlineLargeSize: 32,
    numericSize: 44,
  ),
  density: DesignDensity(
    hairGap: 3,
    tightGap: 6,
    snugGap: 8,
    itemGap: 10,
    blockGap: 12,
    sectionGap: 18,
    majorGap: 24,
    sectionBreak: 48,
    screenPaddingX: 20,
    screenPaddingTop: 16,
    screenPaddingBottom: 24,
    cardPadding: 16,
    chipPaddingX: 8,
    chipPaddingY: 4,
    radiusSm: 8,
    radiusMd: 12,
    radiusLg: 14,
    radiusXl: 20,
    radiusPill: 999,
    controlHeight: 56,
    compactControlHeight: 48,
    tapTarget: 48,
    contentMaxWidth: 480,
    iconSm: 16,
    iconMd: 18,
    iconLg: 22,
    iconXl: 32,
    iconHero: 40,
    thumbSize: 76,
    brandMarkSize: 64,
    avatarSize: 44,
    avatarLargeSize: 54,
    shadowBlur: 22,
    shadowLift: 8,
    softShadowBlur: 14,
    softShadowLift: 4,
    overlayButtonSize: 38,
    cookControlSize: 96,
    heroImageHeight: 300,
    stepImageHeight: 210,
    photoTileSize: 88,
  ),
);

// ---------------------------------------------------------------------------
// 3. 크리스프 페이퍼 — 색·타이포·형태를 한꺼번에 반대편으로
// ---------------------------------------------------------------------------

/// 웜 톤과 둥근 모서리를 걷어낸 고대비 안. 각진 모서리, 얇은 제목, 촘촘한 여백.
/// "따뜻함"이 이 앱에 정말 필요한 성질인지 되묻기 위한 대조군이다.
const crispPaperSpec = DesignSpec(
  id: 'crisp-paper',
  label: '크리스프 페이퍼',
  palette: DesignPalette(
    brightness: Brightness.light,
    ink: Color(0xFF111214),
    slate: Color(0xFF54585F),
    muted: Color(0xFF8B9098),
    surface: Color(0xFFFFFFFF),
    card: Color(0xFFFFFFFF),
    line: Color(0xFFE3E5E8),
    accent: Color(0xFF1B5FD9),
    accentSoft: Color(0xFFE8EFFC),
    onAccent: Color(0xFFFFFFFF),
    wash: Color(0xFFF4F5F7),
    success: Color(0xFF17803D),
    shadow: Color(0x14000000),
    inverseSurface: Color(0xFF111214),
    onInverse: Color(0xFFFFFFFF),
    onInverseMuted: Color(0xB3FFFFFF),
    inverseLine: Color(0x33FFFFFF),
    scrimStrong: Color(0xCC000000),
    scrimSoft: Color(0x66000000),
    overlaySurface: Color(0xE6FFFFFF),
    placeholderFrom: Color(0xFFF0F1F3),
    placeholderTo: Color(0xFFDCDEE2),
    placeholderIcon: Color(0xFF9AA0A8),
  ),
  type: DesignTypography(
    fontFamily: 'Pretendard',
    // 자간을 거의 조이지 않아 글자가 더 또박또박 읽힌다.
    tightTracking: -0.2,
    bodyHeight: 1.55,
    displayHeight: 1.2,
    regular: FontWeight.w400,
    medium: FontWeight.w400,
    semiBold: FontWeight.w500,
    bold: FontWeight.w600,
    extraBold: FontWeight.w600,
    black: FontWeight.w700,
    microSize: 10,
    tinySize: 11,
    smallSize: 12,
    captionSize: 13,
    bodySize: 14,
    labelSize: 14,
    bodyLargeSize: 15,
    leadSize: 17,
    titleSize: 19,
    titleLargeSize: 22,
    heroTitleSize: 24,
    headlineSize: 26,
    headlineLargeSize: 30,
    numericSize: 40,
  ),
  density: DesignDensity(
    hairGap: 2,
    tightGap: 4,
    snugGap: 6,
    itemGap: 8,
    blockGap: 10,
    sectionGap: 14,
    majorGap: 20,
    sectionBreak: 40,
    screenPaddingX: 16,
    screenPaddingTop: 12,
    screenPaddingBottom: 20,
    cardPadding: 14,
    chipPaddingX: 8,
    chipPaddingY: 3,
    // 각진 모서리. 여기만 바꿔도 앱 인상이 가장 크게 달라진다.
    radiusSm: 2,
    radiusMd: 4,
    radiusLg: 6,
    radiusXl: 8,
    radiusPill: 4,
    controlHeight: 48,
    compactControlHeight: 42,
    tapTarget: 48,
    contentMaxWidth: 520,
    iconSm: 16,
    iconMd: 18,
    iconLg: 20,
    iconXl: 28,
    iconHero: 36,
    thumbSize: 68,
    brandMarkSize: 56,
    avatarSize: 40,
    avatarLargeSize: 48,
    shadowBlur: 12,
    shadowLift: 4,
    softShadowBlur: 6,
    softShadowLift: 2,
    overlayButtonSize: 36,
    cookControlSize: 88,
    heroImageHeight: 260,
    stepImageHeight: 190,
    photoTileSize: 80,
  ),
);

// ---------------------------------------------------------------------------
// 4. 넉넉한 키친 — 밀도 축만 실험
// ---------------------------------------------------------------------------

/// 팔레트는 [warmKitchenSpec] 그대로 두고 글자와 여백만 키운 안.
/// 조리대에서 한 걸음 떨어져 보는 상황을 상정했다. 색을 고정했기 때문에
/// "글자·여백만 키우면 정말 읽기 편해지는가"를 단독으로 판단할 수 있다.
const roomyKitchenSpec = DesignSpec(
  id: 'roomy-kitchen',
  label: '넉넉한 키친',
  palette: _warmPalette,
  type: DesignTypography(
    fontFamily: 'Pretendard',
    tightTracking: -0.4,
    bodyHeight: 1.6,
    displayHeight: 1.2,
    regular: FontWeight.w400,
    medium: FontWeight.w500,
    semiBold: FontWeight.w600,
    bold: FontWeight.w700,
    extraBold: FontWeight.w800,
    black: FontWeight.w900,
    microSize: 11,
    tinySize: 13,
    smallSize: 14,
    captionSize: 15,
    bodySize: 17,
    labelSize: 18,
    bodyLargeSize: 19,
    leadSize: 21,
    titleSize: 23,
    titleLargeSize: 26,
    heroTitleSize: 30,
    headlineSize: 32,
    headlineLargeSize: 36,
    numericSize: 56,
  ),
  density: DesignDensity(
    hairGap: 4,
    tightGap: 8,
    snugGap: 12,
    itemGap: 14,
    blockGap: 18,
    sectionGap: 26,
    majorGap: 34,
    sectionBreak: 60,
    screenPaddingX: 22,
    screenPaddingTop: 20,
    screenPaddingBottom: 32,
    cardPadding: 20,
    chipPaddingX: 12,
    chipPaddingY: 7,
    radiusSm: 10,
    radiusMd: 16,
    radiusLg: 18,
    radiusXl: 26,
    radiusPill: 999,
    controlHeight: 64,
    compactControlHeight: 56,
    tapTarget: 56,
    contentMaxWidth: 480,
    iconSm: 20,
    iconMd: 22,
    iconLg: 26,
    iconXl: 38,
    iconHero: 48,
    thumbSize: 88,
    brandMarkSize: 76,
    avatarSize: 52,
    avatarLargeSize: 64,
    shadowBlur: 26,
    shadowLift: 10,
    softShadowBlur: 16,
    softShadowLift: 5,
    overlayButtonSize: 44,
    cookControlSize: 112,
    heroImageHeight: 320,
    stepImageHeight: 230,
    photoTileSize: 100,
  ),
);
